######################################################################
# Automatically generated by qmake (2.01a) Thu Sep 10 09:52:18 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
