######################################################################
# Automatically generated by qmake (2.01a) Thu May 28 07:27:58 2009
######################################################################

TEMPLATE = app
CONFIG += qt
QT += network
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += Downloader.h
SOURCES += Downloader.cpp main.cpp
