
all: list_kern bstree_kern hash_kern

list_kern: list_kern.c
	gcc -o list_kern list_kern.c

bstree_kern: bstree_kern.c
	gcc -o bstree_kern bstree_kern.c

hash_kern: hash_kern.c
	gcc -o hash_kern hash_kern.c
