######################################################################
# Automatically generated by qmake (2.01a) Thu May 28 07:27:58 2009
######################################################################

TEMPLATE = app
CONFIG += qt
QT += xml
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS +=
SOURCES += main.cpp
